# Generated by Django 6.0.6 on 2026-07-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='bill',
        ),
    ]
